version: "3"

services:
 echoip:
    build:
      context: ./
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    ports:
      - '8067:8080'
    networks:
      - caddy

networks:
  caddy:
    external: true

